"""Intial

Revision ID: 13ea3edc1e37
Revises:
Create Date: 2026-03-12 21:45:43.767881

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13ea3edc1e37"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_settings",
        sa.Column("brand_name", sa.String(length=100), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("primary_color", sa.String(length=7), nullable=False),
        sa.Column("accent_color", sa.String(length=7), nullable=False),
        sa.Column("invoice_prefix", sa.String(length=10), nullable=False),
        sa.Column("footer_text", sa.Text(), nullable=True),
        sa.Column("support_email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_brand_settings_id"), "brand_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_brand_settings_internal_id"),
        "brand_settings",
        ["internal_id"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_internal_id"), "users", ["internal_id"], unique=True
    )
    op.create_table(
        "webhook_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_webhook_events_id"), "webhook_events", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_events_internal_id"),
        "webhook_events",
        ["internal_id"],
        unique=True,
    )
    op.create_table(
        "audit_logs",
        sa.Column("entity", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_internal_id"),
        "audit_logs",
        ["internal_id"],
        unique=True,
    )
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tax_id", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_index(
        op.f("ix_clients_internal_id"), "clients", ["internal_id"], unique=True
    )
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contacts_client_id"), "contacts", ["client_id"], unique=False
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_index(
        op.f("ix_contacts_internal_id"),
        "contacts",
        ["internal_id"],
        unique=True,
    )
    op.create_table(
        "contracts",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("billing_cycle", sa.String(length=20), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PAUSED",
                "CANCELLED",
                "EXPIRED",
                name="contractstatus",
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contracts_client_id"),
        "contracts",
        ["client_id"],
        unique=False,
    )
    op.create_index(op.f("ix_contracts_id"), "contracts", ["id"], unique=False)
    op.create_index(
        op.f("ix_contracts_internal_id"),
        "contracts",
        ["internal_id"],
        unique=True,
    )
    op.create_table(
        "invoices",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=True),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SENT",
                "PARTIALLY_PAID",
                "PAID",
                "OVERDUE",
                "VOID",
                name="invoicestatus",
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "total_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "amount_paid", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_number"),
    )
    op.create_index(
        op.f("ix_invoices_client_id"), "invoices", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_contract_id"),
        "invoices",
        ["contract_id"],
        unique=False,
    )
    op.create_index(op.f("ix_invoices_id"), "invoices", ["id"], unique=False)
    op.create_index(
        op.f("ix_invoices_internal_id"),
        "invoices",
        ["internal_id"],
        unique=True,
    )
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=10, scale=3), nullable=False
        ),
        sa.Column(
            "unit_price", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "tax_rate", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "discount", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_items_id"), "invoice_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_items_internal_id"),
        "invoice_items",
        ["internal_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_invoice_items_invoice_id"),
        "invoice_items",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("provider_ref", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "internal_id",
            sa.UUID(),
            nullable=False,
            comment="Public UUID v7 identifier for API consumers.",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(
        op.f("ix_payments_internal_id"),
        "payments",
        ["internal_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payments_invoice_id"),
        "payments",
        ["invoice_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_internal_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(
        op.f("ix_invoice_items_invoice_id"), table_name="invoice_items"
    )
    op.drop_index(
        op.f("ix_invoice_items_internal_id"), table_name="invoice_items"
    )
    op.drop_index(op.f("ix_invoice_items_id"), table_name="invoice_items")
    op.drop_table("invoice_items")
    op.drop_index(op.f("ix_invoices_internal_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_contract_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_client_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_contracts_internal_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_client_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_contacts_internal_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_client_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_index(op.f("ix_clients_internal_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_audit_logs_internal_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(
        op.f("ix_webhook_events_internal_id"), table_name="webhook_events"
    )
    op.drop_index(op.f("ix_webhook_events_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_users_internal_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_brand_settings_internal_id"), table_name="brand_settings"
    )
    op.drop_index(op.f("ix_brand_settings_id"), table_name="brand_settings")
    op.drop_table("brand_settings")
    # ### end Alembic commands ###
